### PR TITLE
V2 - complete rewrite in Vanilla JS

### PR DESCRIPTION
**Pull request by nisarhassan12**
This PR addresses #53 

v2 only ships JS 20.86KB of JS( out of which 10.77KB is the size of huge projects array ) Apart from the scripts needed by tweeter-embeds.

Also, there are some slight design updates this is how the site looks now: 
image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
The Netlify build is failing because we switched from Gatsby to Vanilla JS and Parcel as the module bundler the build script generates a dist/ folder instead of public/

**Comment by nisarhassan12** [comment]
> - I'm personally not a fan about the moving buttons on hover, I prefer a changing color. What are your thoughts about it?

I Agree! what color should I use ?

**Comment by ChristinFrohne** [comment]
> > * I'm personally not a fan about the moving buttons on hover, I prefer a changing color. What are your thoughts about it?
> 
> I Agree! what color should I use ?

use a purple bottom with white font on hover, please :)

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the changes please have a look again.

**Comment by ChristinFrohne** [comment]
- [ ] please delete the left line of the paper plane. It still doesn't fit and I don't think it's necessary 

- [ ] the arrow in the search box isn't centered

- [ ] please add the same border style as elsewhere to the field `sorry we can't find any projects ...`

- [ ] also a `go back` button would be helpful on that view

- [ ] use the same font size for all headlines (35px)  and have a bit more space between the first headline and the paper plane

- [ ] the grey background should end exactly in the middle of the first box 

generally I think that the site looks a bit better on a 90% view. But I guess that rather difficult to adjust, isn't it?

**Comment by nisarhassan12** [comment]
> generally I think that the site looks a bit better on a 90% view. But I guess that rather difficult to adjust, isn't it?

It really depends on how the site is coded and how the things are sized. In our case, it's quite simple and straight forward. It just changing one line CSS. 

I have now made everything a bit smaller.

**Comment by nisarhassan12** [comment]
> use the same font size for all headlines (35px) and have a bit more space between the first headline and the paper plane

I have made the font-size same for both h1 and h2 it is not exactly 35px but it's very close to that.

**Comment by nisarhassan12** [comment]
@ChristinFrohne I have made the changes please have a look again.

**Comment by svenefftinge** [comment]
We decided that while the new version is more performant, going away from Gatsby and TS has other drawbacks (e.g. SEO, accessibility) we would need to take care about manually.

**Pull request closed without merging**
